apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor

  # Airflow metadata DB
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

  # Celery broker + result backend
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow

  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

  # Simple UI auth for internal setups
  AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth