apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow

  # Generate once, keep forever
  AIRFLOW__CORE__FERNET_KEY: "REPLACE_WITH_FERNET_KEY"
  AIRFLOW__WEBSERVER__SECRET_KEY: "REPLACE_WITH_RANDOM_SECRET"